server:
  contextPath: /api
  port: 8090

spring:
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      groupId: kafka-demo-group-query
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: demo.api.command.service.kafka.serialization.ItemEventDeserializer
      autoOffsetReset: latest
      enableAutoCommit: false
      isolationLevel: read_committed
    listener:
      ackMode: MANUAL

kafka:
 demo:
   topic: topic-kafka-demo-topic

management:
  security:
    enabled: false

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    appname: demo-api-query-service
    preferIpAddress: true

zipkinserver:
  ribbon:
    ListOfServers: demo-api-zipkin-service