server:
  servlet:
    context-path: /api
  port: 8089


spring:
  kafka:
    bootstrapServers: kafka:9092
    consumer:
      groupId: kafka-demo-group
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: demo.api.command.service.kafka.serialization.ItemEventDeserializer
      autoOffsetReset: earliest
      enableAutoCommit: false
      isolationLevel: read_committed
    listener:
      ackMode: MANUAL

  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    sender:
      type: web

kafka:
 demo:
  topic: topic-kafka-demo-topic

item:
  descriptionSuffix: TestingPropertyUpdate14
  
management:
  securitymanagement:
    security:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"