#All Common properties accessible to all application goes here.

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "kafka:9092"

management:
  securitymanagement:
    security:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"		  