server:
  servlet:
    context-path: /api
  port: 8090


spring:
  kafka:
    bootstrapServers: kafka:9092
    consumer:
      groupId: kafka-demo-group-query
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: demo.api.command.service.kafka.serialization.ItemEventDeserializer
      autoOffsetReset: latest
      enableAutoCommit: false
      isolationLevel: read_committed
    listener:
      ackMode: MANUAL

kafka:
 demo:
   topic: topic-kafka-demo-topic

management:
  securitymanagement:
    security:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
   
#feign:
#  hystrix:
#    enabled: true
